# Generated by Django 4.2.4 on 2024-02-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='otp',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
