# Generated by Django 4.2.4 on 2024-02-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='otp',
            field=models.CharField(default='', max_length=4),
        ),
    ]
