# Generated by Django 5.0.1 on 2024-02-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0002_person_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='otp',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
    ]
