# Generated by Django 5.0 on 2024-02-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0002_person_country_person_name_alter_person_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
