# Generated by Django 5.0 on 2024-02-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0003_remove_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(default='', max_length=10),
        ),
    ]
